# type: s3
# config:
#   bucket: thanos
#   endpoint: minio.metalmatze-kubecon2019.svc.cluster.local:9000
#   insecure: true
#   access_key: minio
#   secret_key: minio123

apiVersion: v1
kind: Secret
metadata:
  name: thanos-objectstorage
  namespace: metalmatze-kubecon2019
type: Opaque
data:
  thanos.yaml: dHlwZTogczMKY29uZmlnOgogIGJ1Y2tldDogdGhhbm9zCiAgZW5kcG9pbnQ6IG1pbmlvLm1ldGFsbWF0emUta3ViZWNvbjIwMTkuc3ZjLmNsdXN0ZXIubG9jYWw6OTAwMAogIGluc2VjdXJlOiB0cnVlCiAgYWNjZXNzX2tleTogbWluaW8KICBzZWNyZXRfa2V5OiBtaW5pbzEyMwo=
