apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: thanos-querier
  name: thanos-querier
  namespace: metalmatze-kubecon2019
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: thanos-querier
  template:
    metadata:
      labels:
        app.kubernetes.io/name: thanos-querier
    spec:
      containers:
      - args:
        - query
        - --query.replica-label=prometheus_replica
        - --grpc-address=0.0.0.0:10901
        - --http-address=0.0.0.0:9090
        - --store=dnssrv+_grpc._tcp.thanos-store.metalmatze-kubecon2019.svc.cluster.local
        - --store=dnssrv+_grpc._tcp.thanos-receive.metalmatze-kubecon2019.svc.cluster.local
        - --query.replica-label=replica
        image: quay.io/thanos/thanos:master-2019-11-14-a3ab5456
        name: thanos-querier
        ports:
        - containerPort: 10901
          name: grpc
        - containerPort: 9090
          name: http
        readinessProbe:
          httpGet:
            path: /-/ready
            port: 9090
            scheme: HTTP
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 256Mi
